name: Sphinx Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install graphviz - Ubuntu
        run: sudo apt-get install graphviz pandoc
            
      - name: Checkout
        uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.2'
            
      - name: Install python packages
        run: pip install tox
        
      - name: Tox
        run: tox -e docs

      - name: Deploy docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
