# This workflow builds the Docker image and pushes it to GitHub Container Registry (ghcr.io) on push to main or tags.
# No extra secrets are needed; uses GITHUB_TOKEN for authentication.

name: Build and Publish Docker image to GHCR

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mdshw5/pisces:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
