name: Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-latest, macos-latest]

    steps:
      - if: matrix.os == 'ubuntu-latest'
        name: Install graphviz - Ubuntu
        run: |
            sudo apt-get install graphviz pandoc
            
      - if: matrix.os == 'macos-latest'
        name: Install graphviz - MacOS
        run: |
            brew install graphviz pandoc

      - name: Checkout
        uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
            r-version: '3.6.2'
            
      - name: Install python packages
        run: pip install tox
    
      - name: Tox
        run: tox

      - if: matrix.os == 'ubuntu-latest'
        name: Deploy docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
