name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.2'
            
      - name: Install python packages
        run: pip install tox
    
      - name: Tox
        run: tox -e py39
